FROM oven/bun:1.3.5-alpine AS base
WORKDIR /usr/src/app

COPY package.json bun.lock ./

FROM base AS development
RUN bun install --frozen-lockfile

COPY . .
USER bun

EXPOSE 3000
ENTRYPOINT [ "bun", "run", "start" ]

FROM base AS dependencies
RUN bun install --frozen-lockfile --production

FROM base AS building
COPY --from=dependencies /usr/src/app/node_modules ./node_modules

COPY . .
RUN bun run build

FROM alpine:3.23 AS production
WORKDIR /usr/src/app

RUN apk add --no-cache libstdc++ libgcc && \
  addgroup -S graphgroup && adduser -S graphuser -G graphgroup

COPY --from=building --chown=graphuser:graphgroup /usr/src/app/graph .

USER graphuser
EXPOSE 3000
ENTRYPOINT [ "./graph" ]
