FROM oven/bun:1.3.5-alpine AS base
WORKDIR /usr/src/app

# === Dependencies Stage ===
FROM base AS dependencies
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# === Development Stage ===
FROM dependencies  AS development

COPY prisma ./prisma
RUN bunx --bun prisma generate

COPY . .
USER bun

EXPOSE 3000
ENTRYPOINT [ "bun", "run", "start" ]

## === Building Stage ===
FROM dependencies AS building

COPY prisma ./prisma
RUN bunx --bun prisma generate

COPY . .
RUN bun run build

# === Production Stage ===
FROM alpine:3.23 AS production
WORKDIR /usr/src/app

RUN apk add --no-cache libstdc++ libgcc && \
  addgroup -S graphgroup && adduser -S graphuser -G graphgroup

COPY --from=building --chown=graphuser:graphgroup /usr/src/app/graph .
USER graphuser

EXPOSE 3000
ENTRYPOINT [ "./graph" ]
