FROM oven/bun:1.3.5-alpine AS base
WORKDIR /usr/src/app

# === Dependencies Stage ===
FROM base AS dependencies
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# === Prisma Stage ===
FROM dependencies AS prisma
ARG DATABASE_URL="postgresql://dummy:dummy@postgres:5432/dummy"
ENV DATABASE_URL=${DATABASE_URL}

COPY prisma ./prisma
COPY prisma.config.ts ./
RUN bunx --bun prisma generate

# === Development Stage ===
FROM prisma  AS development
COPY . .
USER bun

EXPOSE 3000
ENTRYPOINT [ "bun", "run", "start" ]

## === Building Stage ===
FROM prisma AS building
COPY . .
RUN bun run build

# === Production Stage ===
FROM alpine:3.23 AS production
WORKDIR /usr/src/app

RUN apk add --no-cache libstdc++ libgcc && \
  addgroup -S graphgroup && adduser -S graphuser -G graphgroup

COPY --from=building --chown=graphuser:graphgroup /usr/src/app/graph .
USER graphuser

EXPOSE 3000
ENTRYPOINT [ "./graph" ]
